import { StyleCategory } from './types';

export const STYLE_CATEGORIES: StyleCategory[] = [
  {
    title: '스타일 변경',
    options: [
      { id: 'pixar', label: '픽사', prompt: '이것을 픽사 스타일 캐릭터로 바꿔줘' },
      { id: 'clay', label: '클레이메이션', prompt: '이것을 클레이메이션 캐릭터로 바꿔줘' },
      { id: 'funko', label: '펀코팝', prompt: '이것을 펀코팝 피규어로 바꿔줘' },
      { id: 'lego', label: '레고', prompt: '이것을 레고 미니피규어로 바꿔줘' },
      { id: 'lowpoly', label: '로우폴리 3D', prompt: '이것을 로우폴리 3D 모델로 바꿔줘' },
      { id: 'watercolor', label: '수채화', prompt: '이것을 수채화 그림으로 바꿔줘' },
      { id: 'lineart', label: '라인 아트', prompt: '이것을 라인 아트 드로잉으로 바꿔줘' },
      { id: 'pixelart', label: '픽셀 아트', prompt: '이것을 픽셀 아트로 바꿔줘' },
      { id: 'sticker', label: '다이컷 스티커', prompt: '이것을 흰색 테두리가 있는 다이컷 스티커로 바꿔줘' },
      { id: 'sketch', label: '연필 스케치', prompt: '이것을 연필 스케치로 바꿔줘' },
      { id: 'popart', label: '팝아트', prompt: '이것을 팝아트 그림으로 바꿔줘' },
      { id: 'vaporwave', label: '베이퍼웨이브', prompt: '이것을 베이퍼웨이브 스타일 이미지로 바꿔줘' },
      { id: 'ukiyo-e', label: '우키요에', prompt: '이것을 일본 우키요에 목판화 스타일로 바꿔줘' },
      { id: 'steampunk', label: '스팀펑크', prompt: '이것을 스팀펑크 스타일의 기계 장치가 있는 모습으로 바꿔줘' },
      { id: 'stained-glass', label: '스테인드글라스', prompt: '이것을 스테인드글라스 창문처럼 만들어줘' },
    ],
  },
  {
    title: '배경 변경',
    options: [
      { id: 'forest', label: '마법의 숲', prompt: '이것을 아름다운 마법의 숲에 배치해 줘' },
      { id: 'cyberpunk', label: '사이버펑크 도시', prompt: '이것을 미래형 사이버펑크 도시에 배치해 줘' },
      { id: 'beach', label: '열대 해변', prompt: '이것을 해질녘 열대 해변에 배치해 줘' },
      { id: 'space-nebula', label: '우주 성운', prompt: '이것을 다채로운 성운이 있는 우주 공간에 배치해 줘' },
      { id: 'underwater-city', label: '해저 도시', prompt: '이것을 빛나는 해저 도시에 배치해 줘' },
      { id: 'volcanic-plains', label: '화산 지대', prompt: '이것을 용암이 흐르는 화산 지대에 배치해 줘' },
      { id: 'floating-islands', label: '하늘섬', prompt: '이것을 하늘에 떠 있는 섬 위에 배치해 줘' },
      { id: 'enchanted-library', label: '마법 도서관', prompt: '이것을 고대의 마법 책으로 가득한 도서관에 배치해 줘' },
    ],
  },
  {
    title: '포즈/행동 변경',
    options: [
      { id: 'wave', label: '손 흔들기', prompt: '이 캐릭터가 손을 흔들게 해줘' },
      { id: 'thumbsup', label: '엄지척', prompt: '이 캐릭터가 엄지척을 하게 해줘' },
      { id: 'jump', label: '기뻐서 점프', prompt: '이 캐릭터가 기뻐서 점프하게 해줘' },
      { id: 'thinking', label: '생각하는 중', prompt: '이 캐릭터가 깊은 생각에 잠긴 포즈를 취하게 해줘' },
      { id: 'dancing', label: '춤추기', prompt: '이 캐릭터가 즐겁게 춤을 추게 해줘' },
      { id: 'fighting-stance', label: '전투 준비 자세', prompt: '이 캐릭터가 역동적인 전투 준비 자세를 취하게 해줘' },
      { id: 'reading-book', label: '독서', prompt: '이 캐릭터가 흥미롭게 책을 읽고 있는 모습으로 바꿔줘' },
      { id: 'playing-guitar', label: '기타 연주', prompt: '이 캐릭터가 기타를 연주하게 해줘' },
    ],
  },
  {
    title: '의상/액세서리 변경',
    options: [
      { id: 'sunglasses', label: '선글라스 추가', prompt: '이 캐릭터에게 멋진 선글라스를 씌워줘' },
      { id: 'piratehat', label: '해적 모자', prompt: '이 캐릭터에게 해적 모자를 씌워줘' },
      { id: 'superhero', label: '슈퍼히어로 의상', prompt: '이 캐릭터를 슈퍼히어로처럼 입혀줘' },
      { id: 'knight-armor', label: '기사 갑옷', prompt: '이 캐릭터에게 빛나는 기사 갑옷을 입혀줘' },
      { id: 'wizard-robe', label: '마법사 로브', prompt: '이 캐릭터에게 별이 수놓아진 마법사 로브를 입혀줘' },
      { id: 'sci-fi-visor', label: '사이파이 바이저', prompt: '이 캐릭터에게 미래적인 사이파이 바이저를 씌워줘' },
      { id: 'detective-coat', label: '탐정 코트', prompt: '이 캐릭터에게 트렌치코트와 중절모를 입혀 탐정처럼 만들어줘' },
      { id: 'royal-crown', label: '왕관', prompt: '이 캐릭터의 머리에 화려한 왕관을 씌워줘' },
    ],
  },
  {
    title: '감정 변경',
    options: [
      { id: 'happy', label: '행복하게', prompt: '이 캐릭터를 행복해 보이게 해줘' },
      { id: 'sad', label: '슬프게', prompt: '이 캐릭터를 슬퍼 보이게 해줘' },
      { id: 'surprised', label: '놀라게', prompt: '이 캐릭터를 놀라 보이게 해줘' },
      { id: 'determined', label: '결의에 차게', prompt: '이 캐릭터의 표정을 결의에 찬 모습으로 바꿔줘' },
      { id: 'mischievous', label: '장난기 가득', prompt: '이 캐릭터가 장난기 가득한 미소를 짓게 해줘' },
      { id: 'serene', label: '평온하게', prompt: '이 캐릭터를 평온하고 고요한 표정으로 만들어줘' },
      { id: 'courageous', label: '용감하게', prompt: '이 캐릭터를 용감하고 대담해 보이게 해줘' },
      { id: 'confused', label: '어리둥절하게', prompt: '이 캐릭터를 어리둥절한 표정으로 만들어줘' },
    ],
  },
  {
    title: '사물 추가/제거',
    options: [
      { id: 'addcat', label: '고양이 추가', prompt: '이 캐릭터 옆에 귀여운 고양이를 추가해 줘' },
      { id: 'removehat', label: '모자 제거', prompt: '이 캐릭터의 모자를 제거해 줘' },
      { id: 'addsword', label: '검 추가', prompt: '이 캐릭터의 손에 검을 쥐여줘' },
      { id: 'robot-companion', label: '로봇 동료 추가', prompt: '이 캐릭터 옆에 작고 친근한 로봇 동료를 추가해 줘' },
      { id: 'magical-staff', label: '마법 지팡이 추가', prompt: '이 캐릭터의 손에 빛나는 마법 지팡이를 쥐여줘' },
      { id: 'floating-crystals', label: '마법 수정 추가', prompt: '이 캐릭터 주위에 마법의 수정들이 떠다니게 해줘' },
      { id: 'add-backpack', label: '배낭 추가', prompt: '이 캐릭터에게 모험가용 배낭을 메게 해줘' },
      { id: 'add-coffee', label: '커피 추가', prompt: '이 캐릭터의 손에 따뜻한 커피 한 잔을 들려줘' },
    ],
  },
];
